extends Resource
class_name Pokeballs

enum Pokeball {POKE, GREAT, ULTRA, MASTER, SAFARI, FAST, LEVEL, LURE, HEAVY, LOVE, FRIEND, MOON, SPORT, NET, DIVE, NEST, REPEAT, TIMER, LUXURY, PREMIER, DUSK, HEAL, QUICK, CHERISH, PARK, DREAM, BEAST, STRANGE, HISUI_POKE, HISUI_GREAT, HISUI_ULTRA, FEATHER, WING, JET, HISUI_HEAVY, LEADEN, GIGATON, ORIGIN}
